POST http:localhost:3000/auth/refresh-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoibWFya0Bkb2UuY29tIiwiaWF0IjoxNzU1NTkzMTI1LCJleHAiOjE3NTU1OTY3MjUsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.NM-s18PfY1dNj3C2OQN5f1POzySR2XVtrrnwxTjqzW4

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImlhdCI6MTc1NTU5MzEyNSwiZXhwIjoxNzU1Njc5NTI1LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.jb0VIIwXY7thHzRqEhkJRkiNmzI4aLR8r-34P7OUUuk"
}